name: 'Java CI with Maven'
on:
  workflow_call:
    inputs:
      ref_branch:
        type: string
        required: true
        description: 'Referance branch or tag'
      environment_name:
         type: string
         required: true
         description: 'Environment name'
      instance_name:
        type: string
        required: true
        description: 'Instance name'
      instance_type:
        type: string
        required: true
        description: 'Instance type'
      deploy_version:
        type: string
        required: true
        description: 'Deploy with War/Jar version'
      upgrade_version:
        type: string
        required: true
        description: 'Upgrade with War/Jar version'
      deploy_jdk_version:
        type: string
        required: true
        description: 'Depoy with JDK version'
      upgrade_jdk_version:
        type: string
        required: true
        description: 'Upgrade with JDK version'
  workflow_dispatch:
    inputs:
      ref_branch:
        type: string
        required: true
        description: 'Referance branch or tag'
        default: common_nssm_col_pub

      environment_name:
        type: choice
        required: true
        description: 'Environmnt name'
        options: 
          - devopsazure
          - devops
          - lab1zus1
          - dev1zus1

      instance_name:
        type: text
        required: true
        description: 'Instance name'

      instance_type:
        type: choice
        required: true
        description: 'Instance type'
        options:
          - Collaborate
          - Publisher
          - Hybrid
          - Microservice

      deploy_version:
        type: text
        required: true
        description: 'Deploy with War/Jar version'

      upgrade_version:
        type: text
        required: true
        description: 'Upgrade with War/Jar version'

      deploy_jdk_version:
        type: choice
        required: true
        default: jdk-17.0.8+8
        description: 'Deploy with JDK version'
        options:
          - jdk-17.0.8+8
          - jdk-11.0.11+9
          
      upgrade_jdk_version:
        type: choice
        required: true
        default: jdk-17.0.8+8
        description: 'Upgrade with JDK version'
        options:
          - jdk-17.0.8+8
          - jdk-11.0.11+9
        
  pull_request:
    branches: [ "master" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # testing 1
    # testing 2
    
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

        
